# Generated by Django 5.1.5 on 2025-01-30 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='phone_number',
            field=models.CharField(help_text='Enter phone number with country code (e.g., +8801712345678)', max_length=15, null=True),
        ),
    ]
