# Generated by Django 5.1.5 on 2025-02-03 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0002_message_phone_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='ResultModel',
        ),
    ]
